stages:
  get_train_data:
    cmd: python src\get_data.py Train
    deps:
    - src\get_data.py
    outs:
    - data\raw.csv
  process_data:
    cmd: >-
      python src\process_data.py Train &&
      python src\test_data.py
    deps:
    - src\process_data.py
    - data\raw.csv
    outs:
    - data\processed.csv
  split_date:
    cmd: python src\split_data.py
    deps:
    - src\split_data.py
    - data\processed.csv
    outs:
    - data\X_train.csv
    - data\Y_train.csv
    - data\X_test.csv
    - data\Y_test.csv
  train_model:
    cmd: python src\train.py
    deps:
    - src\train.py
    - data\X_train.csv
    - data\Y_train.csv
    - data\X_test.csv
    - data\Y_test.csv
    outs:
    - model\model.pkl
  predict:
    cmd: python src\predict.py
    deps:
    - src\predict.py
    - model\model.pkl
    - data\X_test.csv
    outs:
    - data\results.csv
  evaluate:
    cmd: python src\evaluate.py
    deps:
    - data\results.csv
    metrics:
    - scores.json:
        cache: false
    plots:
    - plots.csv:
        x: Survived
        y: Prediction
        title: Displaying accuracy
        template: confusion 
        x_label: Actual
        y_label: Prediction